### ISSUE TITLE
Update Node.js version from 8 to 10 for Node Rotation Lambdas

### ISSUE THREAD

**Issue by buck06191** [guardian/elasticsearch-node-rotation#44]
As per https://github.com/guardian/ophan/issues/3491, Node.js 8 will be reaching the end of its lifetime on Dec 31st 2019 and there are a number of lambda functions that need updating to Node.js 10 in the Elastic Node Rotation step functions.

**Comment by jacobwinch** [comment]
Closing this as @buck06191 has upgraded to Node10 [here](https://github.com/guardian/elasticsearch-node-rotation/pull/46) (thanks!)
