### ISSUE TITLE
Failure due to AWS API throttling

### ISSUE THREAD

**Issue by simone-smith** [guardian/elasticsearch-node-rotation#45]
ENR failed at the `removeNode` step with the following error: 

> 2019-11-11T06:52:20.802Z	a0dc96a7-3bfc-4a6d-8d6c-5793ae8e76cf	{"errorMessage":"Rate exceeded","errorType":"Throttling","stackTrace":["Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:50:29)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)","Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","/var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}

This left us with one extra node. 

We've checked the logs for the last 2 weeks and this is the only instance of this error, but we just wanted to flag it up in case it reoccurs.

**Comment by rtyley** [comment]
This happened again today at 7:04am:

https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:021353022223:execution:Elasticsearch-Node-Rotation-ophan:9bb72fde-582f-e81b-dec9-503b0b0f9a30_3fd85c22-77e6-39a5-42e8-be80675a27d6

![image](https://user-images.githubusercontent.com/52038/71619919-bba2a300-2bbe-11ea-9e58-19a177e20a14.png)

https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=/aws/lambda/enr-reattach-old-instance-PROD;stream=2019/12/31/[$LATEST]65545c0d567d45e1abf9b3fd0cde9293;start=2019-12-30T07:04:50Z

```
{
    "errorType": "Throttling",
    "errorMessage": "Rate exceeded",
    "code": "Throttling",
    "message": "Rate exceeded",
    "time": "2019-12-31T07:04:50.875Z",
    "requestId": "d69b52d7-2b9b-11ea-81a1-93f91f37c375",
    "statusCode": 400,
    "retryable": true,
    "stack": [
        "Throttling: Rate exceeded",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:50:29)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

Although ENR retries SSM calls, it doesn't seem to use that approach on other AWS API calls. It should probably retry when it receives a throttle failure?

**Comment by buck06191** [comment]
This happened again yesterday at 7:43am

https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:021353022223:execution:Elasticsearch-Node-Rotation-ophan:63102d43-77df-bbda-5460-574a32b9531b_5e159438-5d78-770c-ab3c-aaddb29692ce

![image](https://user-images.githubusercontent.com/9122944/71660048-b28e0f00-2d41-11ea-9413-222d30e45bc6.png)

It failed at the `RemoveNode` stage this time and gave the below error message.


```json
{
  "error": "Throttling",
  "cause": {
    "errorType": "Throttling",
    "errorMessage": "Rate exceeded",
    "trace": [
      "Throttling: Rate exceeded",
      "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:50:29)",
      "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
      "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
      "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)",
      "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
      "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
      "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
      "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
      "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)",
      "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
  }
}
```

**Comment by jacobwinch** [comment]
Closing this as https://github.com/guardian/elasticsearch-node-rotation/pull/49 seems to have addressed it (thanks @buck06191 and @rtyley).
