### ISSUE TITLE
Become agnostic to how many ASGs are used in a cluster

### ISSUE THREAD

**Issue by rtyley** [guardian/elasticsearch-node-rotation#48]
It would be nice if we didn't have so much configuration around how many ASGs are in the Elasticsearch cluster - with #47 we added support for a _3rd_ ASG (warm nodes, in a [hot/warm](https://www.elastic.co/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management) configuration) - that comes after https://github.com/guardian/elasticsearch-node-rotation/pull/27 which added support for a 2nd ASG (dedicated master nodes). Another ASG might be introduced with [Coordinating nodes](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#coordinating-node) for instance...!

In principle, rather than identifying an Elastic cluster by it's auto-scaling group, it should be possible to identify it by it's AWS Tags (App, Stack & Stage). With that information, you can find all EC2 instances in the cluster - and each EC2 instance is already automatically tagged with information about which cluster it's in, which is how Ophan's [Node-Protector](https://github.com/guardian/ophan/blob/a60f21904dbead70f662f02543473935965adcc9/trigr/app/elasticsearch/protector/InstanceProtection.scala#L86-L101) works out which ASGs to act upon.

One sticking point might be updating the `ElasticsearchAdminAsgPolicy` to give the correct access without the ASG names being explicitly passed to the cloudformation. Some ways around this:

* be more relaxed, and use a `*`on the Resource permission
* generate a security group that users can apply to their ASGs to grant access.

**Comment by rtyley** [comment]
@mbarton said:

> I noticed there's separate cron expressions for the data node, warm node and master autoscaling groups. Do you have them set to different expressions and is it important they rotate at different times?

The `elasticsearch-node-rotation` Step Function has code that means it only allows **one execution** running at a time:

https://github.com/guardian/elasticsearch-node-rotation/blob/ea9bd7e533720e5e75f8a62efb6b19783d30fb9d/src/autoScalingGroupCheck.ts#L10-L16

...so we have had to be careful to schedule our cron expressions so that the executions don't overlap:

![image](https://user-images.githubusercontent.com/52038/118638819-231abc00-b7cf-11eb-8a39-9befe5e35446.png)

![image](https://user-images.githubusercontent.com/52038/118638973-4fced380-b7cf-11eb-9cb9-e831f5368922.png)

![image](https://user-images.githubusercontent.com/52038/118638859-2dd55100-b7cf-11eb-85c5-314ff2184df3.png)

...having to configure 3 different crons is not much fun though, it would be nice if we could avoid that!

**Comment by mbarton** [comment]
@rtyley and I discussed this yesterday. His proposal was to remove the separate schedules and finding the AutoScaling group with the oldest instance and rotate that one. We'd then tweak the single expression to be regular enough to keep instances fresh
