### ISSUE TITLE
Only Data nodes should require a 'shard-migration'/'no-documents' check for shutdown

### ISSUE THREAD

**Issue by rtyley** [guardian/elasticsearch-node-rotation#60]
This follows on from issue #31 & PR #33 - which made this change:

* **BEFORE** : You can't shutdown any node while any shard migration is taking place
* **AFTER** : You _can_ shutdown a [Data node](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/modules-node.html#data-node) so long as it has **no documents**, regardless of any shard migration taking place

I'd like to suggest that:

* the `ShardMigrationCheck` should become a `DataNodeEmpty` check
* the check should **only** occur for Data nodes

If a replacement node has already been attached to the cluster, it should surely be fine to shutdown any node that has no data, regardless of whether shard-migrations are taking place.

The current code (which I wrote!) explicitly fails the `ShardMigrationCheck` if the node is a master node and shard migrations are taking place (Ophan's shard migrations [_take ages_](https://github.com/guardian/elasticsearch-node-rotation/issues/55#issue-744928318)) - but I now believe this is unnecessary:

https://github.com/guardian/elasticsearch-node-rotation/blob/be01a6b7b19850f48cc380b92d007c920123e261/src/shardMigrationCheck.ts#L10-L15

### Motivation

In Ophan we have dedicated '[master-eligible](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/modules-node.html#master-node)' nodes, and the rotation of those nodes failed on the `ShardMigrationCheck` three times in the space of 1 week:

| [24th December](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:021353022223:execution:ophan-Elasticsearch-Node-Rotation-PROD:78ea3f34-5fb3-84e4-667b-f3e271a79fb7_d4e8a0ca-96af-3d9a-375a-803f72dc65be) | [29th December](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:021353022223:execution:ophan-Elasticsearch-Node-Rotation-PROD:858a7565-26dc-451c-809d-4429099921d7_81aa67c0-068d-c2a9-59e4-b78bbfff121f)  | [31st December](https://eu-west-1.console.aws.amazon.com/states/home?region=eu-west-1#/executions/details/arn:aws:states:eu-west-1:021353022223:execution:ophan-Elasticsearch-Node-Rotation-PROD:4dfb7407-2e83-9e56-a285-0f09881b7694_6b94662a-ac43-5792-1a35-408549e090c8) |
| ------------- | ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/52038/103656436-80b91500-4f60-11eb-9231-6455e9e33a15.png" width="300">  | <img src="https://user-images.githubusercontent.com/52038/103652931-b6a7ca80-4f5b-11eb-91d2-c876ec308516.png" width="300">  | <img src="https://user-images.githubusercontent.com/52038/103652974-c45d5000-4f5b-11eb-9792-e6681adf3ee6.png" width="300">  |

There's no good reason for us to be running the `ShardMigrationCheck` against those non-Data nodes!

**Comment by jacobwinch** [comment]
> The current code (which I wrote!) explicitly fails the `ShardMigrationCheck` if the node is a master node and shard migrations are taking place (Ophan's shard migrations [_take ages_](https://github.com/guardian/elasticsearch-node-rotation/issues/55#issue-744928318)) - but I now believe this is unnecessary:

According to [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cluster.html#modules-cluster):

> One of the main roles of the master is to decide which shards to allocate to which nodes, and when to move shards between nodes in order to rebalance the cluster.

However, I'm unsure if the current master node performs any _ongoing_ work after making the initial decision to move a shard. If so, I worry that shutting it down during this period may introduce problems. @rtyley @sihil @davidfurey - I don't suppose any of you have a better understanding of the master node's role in migrating shards?

**Comment by jacobwinch** [comment]
> However, I'm unsure if the current master node performs any _ongoing_ work after making the initial decision to move a shard. If so, I worry that shutting it down during this period may introduce problems. @rtyley @sihil @davidfurey - I don't suppose any of you have a better understanding of the master node's role in migrating shards?

@jamie-lynch and I discussed this with @sihil, who was confident that the `master` node could be shutdown even if shard relocations were in progress. I've confirmed that this works fine by testing https://github.com/guardian/elasticsearch-node-rotation/pull/61 against the Central ELK stack.

**Comment by jacobwinch** [comment]
@rtyley - I've [merged a small change](https://github.com/guardian/elasticsearch-node-rotation/pull/61) which should stop these regular failures from disrupting the Ophan team. This has been [deployed](https://riffraff.gutools.co.uk/deployment/view/c4a5a66c-49ef-4ce9-a671-8b7ebddfa0cb) to all accounts using this tool.

I agree with your wider point that the same checks need not apply to all node-types, so I've opened [another issue](https://github.com/guardian/elasticsearch-node-rotation/issues/62) to capture the restructuring work required. Whilst investigating this issue we also noticed some master-eligible-specific checks which we ought to run (but are currently missing) e.g. https://github.com/guardian/elasticsearch-node-rotation/issues/64.

I'll close this issue for now as I think the remaining work suggested is captured by other issues, but feel free to re-open this if you think I've missed something.
